import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/context/UserContext";
import { SocektContextProvider } from "@/context/SocketContext";
import { DisasterContextProvider } from "@/context/DisasterContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Guardian-Eye",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserContextProvider>
          <DisasterContextProvider>
            <SocektContextProvider>
              {children}
              <Toaster position="top-right"/>
              </SocektContextProvider>
          </DisasterContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
